// <auto-generated />
using System;
using Informer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Informer.Data.Migrations
{
    [DbContext(typeof(InformerDbContext))]
    [Migration("20260806082248_AddSeverityAndToastPolicy")]
    partial class AddSeverityAndToastPolicy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("Informer.Core.Entities.ApiKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Informer.Core.Entities.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitMaxRequests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireApiKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowErrorToasts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInfoToasts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowWarningToasts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToastDisplaySeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ListenPort = 5005,
                            RateLimitMaxRequests = 20,
                            RateLimitWindowSeconds = 10,
                            RequireApiKey = true,
                            RetentionDays = 30,
                            ShowErrorToasts = true,
                            ShowInfoToasts = true,
                            ShowWarningToasts = true,
                            ToastDisplaySeconds = 8
                        });
                });

            modelBuilder.Entity("Informer.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Sender");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
